try {
  // Manejar el c칩digo
} catch (err) {
  // Se utiliza el par치metro `err`
}

//El par치metro opcional de catch permite omitir el error si es necesario.
try {
  // Manejar el c칩digo
} catch {
  // Manejar el error sin el par치metro.
}

//Aunque siempre es recomendable manejar el error como par치metro, ya que tiene m치s informaci칩n del problema.

const prepareIceCream = money => {
  /*PROMESA*/
  return new Promise((resolve, reject) => {
    if (money >= 500) {
      //3. Si el dinero que ingresaste es mayor o igual a 500,
      //entonces te preparamos el helado. El proceso toma 6 segundos.
      console.log('Estamos preparando tu helado...');
      setTimeout(() => {
        resolve('Aqu칤 est치 tu helado 游꼱');
      }, 2000);
    } else {
      //3. Si el dinero es menor a 500, lo sentimos, no te alcanza
      reject('Ups!, creo que no tienes dinero suficiente 游눯');
    }
  });
};

const buyIceCream = async money => {
  /*FUNCI칍N AS칈NCRONA*/
  try {
    console.log('Bienvenido a mundo Helados!');
    //2. Esperas aqu칤 mientras env칤amos el dinero, lo verifican y te preparan el helado
    const result = await prepareIceCream(money);
    //4. Imprimimos tu pedido! si todo sali칩 bien.
    console.log(result);
    console.log('Gracias por tu compra!');
  } catch (e) {
    //4. Te decimos que no sali칩 bien el proceso porque tu dinero no es suficiente.
    console.log(e);
  }
};

buyIceCream(500); //1. llamas a la funcion comprar helado e Ingresas el dinero

/*----------------------------------------------------------------*/

//Estos ejemplos se diferencian en que uno usa try and catch en la function async para controlar el resultado de la promesa (Helados) y el otro usa un condicional ternario (Clase) el cual usa menos espacio que el condicional ordinario.

const fnAsync = () => {
  //4) Ejecuta Promesa
  return new Promise((resolve, reject) => {
    //5)Retorna uno de los 2 valores.
    true //6) Yes resolve = true, false = reject.
      ? setTimeout(() => resolve('AsynC!!'), 2000) //7) Retorna setTimeout que dentro tiene una funci칩n anonima que tiene un "String" con retraso de 2 segundos.
      : reject(new Error('Error')); //
  });
};

const anotherFn = async () => {
  //2) Ejecutar function async
  const somethig = await fnAsync(); //3) Invocando Promesa
  console.log(somethig); //8) Imprime
  console.log('Hello'); //9) Imprime
};

console.log('before');
anotherFn(); //1) Invocaci칩n
console.log('After');

/**Detallazos | Detallote**/

// `anotherFn();` se esta ejecutando y no interrumpe ni bloquea a `console.log("After");` a pesar que esta sea la 3춿 en ejecutarse.

// ```jsx
// before //1춿 Bien
// After //Aunque esta 3춿 anotherFn tarda 2 seg extra, entonces esta prosigue como si nada
// AsynC!! //2춿 Al fin llega
// Hello // **No lleg칩 antes porque await detuvo todo dentro de la function async hasta que se completar치 la promesa prosiguio con todo lo dem치s dentro de la function async**.

// What if? | Si Hello se moviera de lugar dentro de const anotherFn = async () => {}.
// Esto pruebas le dan mucho sentido a **[un p치rrafo](https://www.notion.so/21-ES8-Funciones-As-ncronas-3b27e1c6a6134af8b99ff399f9c37fc8?pvs=21)**.
// ```

// Usamos `setTimeout();` para generar la tardanza a la que se enfrenta una funci칩n as칤ncrona.

// En el mundo laboral no necesitamos retardar, ya que hay cosas pesadas en descargarse (APIs).
